version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crp424nl6uso19k2ut56/catgpt:1"
    restart: always
    network_mode: "host"
  
  unifiedagent:
    container_name: unifiedagent
    image: "cr.yandex/yc/unified-agent"
    environment:
      FOLDER_ID: "b1gi3jo0sam0o77lva2p"
    restart: always
    network_mode: "host"
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d
